a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
print(f"Addition: {a+b}")
print(f"Subtraction: {a-b}")
print(f"Multiplication: {a*b}")
print(f"Divison: {a/b}")